#!/bin/bash

status=$(nmcli g | grep -v STATE| awk '{print ($1)}')
essid=$(nmcli c | grep wlan0 | awk '{print ($1)}')

if [[ "$1" == "-stat" ]]; then
    echo $status
elif [[ "$1" == "--ESSID" ]]; then
	echo $essid
fi
